# Generated by Django 4.2.5 on 2023-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TO', 'Troca de óleo'), ('VA', 'Troca de válvula'), ('BA', 'Balanceamento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tituto',
            field=models.CharField(max_length=100),
        ),
    ]
