# Generated by Django 4.2.5 on 2023-09-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_alter_categoriamanutencao_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='tituto',
            new_name='titulo',
        ),
    ]
