# Generated by Django 4.2.5 on 2023-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TO', 'Troca de óleo'), ('VA', 'Troca de válvula'), ('BA', 'Balanceamento'), ('LV', 'Lavegem'), ('LA', 'Lava e aspira')], max_length=100),
        ),
    ]
