# Generated by Django 4.2.5 on 2023-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_alter_categoriamanutencao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('Troca de óleo', 'Troca Oleo'), ('Troca de válvula', 'Troca Valvula'), ('Balanceamento', 'Balanceamento'), ('Lavegem', 'Lavagem'), ('Lava e aspira', 'Lava Aspira')], max_length=100),
        ),
    ]
